@baseUrl = https://api.themoviedb.org/3

@token = eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiY2IxODRhMzE3MzM1YWQ5M2RhMDBmNTQzYWI0NGYwNCIsInN1YiI6IjVlOGU1NTYxZmRjMTQ2MDAxMzQ0MzlmMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.GwX3fem9q9Hm3TXv6Z5H5YEZgsBBEGqEZBCK68tTpwE
@api_key = bcb184a317335ad93da00f543ab44f04

@contentType = application/json;charset=utf-8

GET {{baseUrl}}/movie/popular?api_key={{api_key}}&language=en-US&page=1
Content-Type: {{contentType}}